version: "2"

services:
  redis_bot:
    image: redis:latest

    container_name: redis_bot

    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    volumes:
      - redis_bot_data:/data

    restart: on-failure

  bot:
    build: .

    volumes:
      - .:/src

    command: python -m src.main

    env_file:
      - .env

    depends_on:
      - redis_bot

    restart: on-failure

volumes:
  redis_bot_data:
